# config/camera_info_hd.yaml
image_width: 1280
image_height: 720
camera_name: virtual_camera_hd
camera_matrix: #内参矩阵
  rows: 3
  cols: 3
  # 内参
  #[fx,  0,  cx,  fx:x方向焦距 cx:图像宽度/2 = 1280/2
  # 0,  fy, cy,   fy:y方向焦距 cy:图像高度/2 = 720/2
  # 0,   0,  1]
  #fx, fy (焦距，单位：像素)，表示相机焦距转换成像素单位的长度，fx = 焦距(mm) × 传感器宽度(像素) / 传感器物理宽度(mm)
  # 通常 fx ≈ fy，如果不等说明像素不是正方形，数值范围：普通相机 500-2000，广角相机 200-500，长焦相机 2000-10000
  # cx, cy (主点坐标，单位：像素)
  # 光轴与图像平面的交点，通常是图像中心
  # 对于 640x480 图像：cx ≈ 320, cy ≈ 240
  # 实际意义：图像的光学中心，可能与几何中心有微小偏移
  data: [1000.0, 0.0, 640.0, 
         0.0, 1000.0, 360.0, 
         0.0, 0.0, 1.0]

distortion_model: "plumb_bob"
# 如果镜头不是理想的小孔，会产生畸变
# data: [k1, k2, p1, p2, k3]
# 径向畸变 (k1, k2, k3)
# 现象：直线变弯曲，越靠近边缘越明显
# 桶形畸变 (k1 < 0)：图像向外膨胀
# 枕形畸变 (k1 > 0)：图像向内收缩
# 切向畸变 (p1, p2)
# 现象：图像看起来"倾斜"
# 原因：镜头与传感器不平行
# 典型数值范围：
# 普通手机相机：k1 = -0.2 ~ -0.4 (通常有桶形畸变)
# 工业相机：k1 = -0.1 ~ -0.3
# 高质量镜头：k1 = -0.05 ~ -0.1
# 鱼眼镜头：k1 = -0.5 ~ -2.0
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
# 校正矩阵
# 校正矩阵用于立体视觉或多相机系统中，将不同相机的图像"对齐"到同一个平面上。
# 单目相机中通常为单位矩阵（因为不需要与其他相机对齐）
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 
         0.0, 1.0, 0.0, 
         0.0, 0.0, 1.0]
#投影矩阵 将3D点投影到2D图像
# [fx,  0,  cx,  0,    # 这行：x方向投影
#  0,  fy, cy,  0,    # 这行：y方向投影  
#  0,   0,  1,  0]    # 这行：齐次坐标归一化
projection_matrix:
  rows: 3
  cols: 4
  data: [1000.0, 0.0, 640.0, 0.0, 
         0.0, 1000.0, 360.0, 0.0, 
         0.0, 0.0, 1.0, 0.0]